### ISSUE TITLE
builder.prerender() has been removed.

### ISSUE THREAD

**Issue by orefalo** [malynium/svelte-adapter-github#1]
Hi, getting this error...

```
> Using svelte-adapter-github
> builder.prerender() has been removed. Prerendering now takes place in the build phase — see builder.prerender and builder.writePrerendered
    at Object.prerender (file:///Users/orefalo/GitRepositories/svelte-related/svelte-splitpanes/node_modules/@sveltejs/kit/dist/chunks/index4.js:161:10)
    at adapt (file:///Users/orefalo/GitRepositories/svelte-related/svelte-splitpanes/node_modules/svelte-adapter-github/index.js:21:18)
    at adapt (file:///Users/orefalo/GitRepositories/svelte-related/svelte-splitpanes/node_modules/@sveltejs/kit/dist/chunks/index4.js:180:8)
    at file:///Users/orefalo/GitRepositories/svelte-related/svelte-splitpanes/node_modules/@sveltejs/kit/dist/cli.js:935:11
```

**Comment by j4w8n** [comment]
Oh wow! I've neglected this repo. And now realizing I should've forked svelte's repo, instead of cloning, so I could sync their updates.

Working to resolve.

**Comment by nickmura** [comment]
Bruh

**Comment by j4w8n** [comment]
Ok, if you haven't already abandoned this adapter (and I wouldn't blame you), I finally found some time to get this straightened out. Try installing the latest version. I've pushed my own static site to test, and all seems good.

@orefalo @nickmura
